//! # Cargo.toml Generator
//!
//! Generates the `Cargo.toml` manifest for the generated Rust project.
//!
//! The dependencies included vary based on the project configuration:
//!
//! - **Always**: axum, sea-orm, serde, tokio, tracing, uuid, etc.
//! - **Auth enabled**: jsonwebtoken, axum-extra (typed headers), bcrypt
//! - **PostgreSQL**: sqlx with `postgres` feature
//! - **MySQL**: sqlx with `mysql` feature
//! - **SQLite**: sqlx with `sqlite` feature
//! - **OpenAPI**: utoipa, utoipa-swagger-ui
//! - **CORS**: tower-http with `cors` feature
//! - **Validator**: validator crate for DTO validation

use imortal_ir::{AuthStrategy, DatabaseType};

use crate::context::GenerationContext;
use crate::{FileType, GeneratedFile};

// ============================================================================
// Public API
// ============================================================================

/// Generate the `Cargo.toml` file for the generated project.
pub fn generate_cargo_toml(ctx: &GenerationContext) -> Vec<GeneratedFile> {
    let content = build_cargo_toml(ctx);
    vec![GeneratedFile::new("Cargo.toml", content, FileType::Toml)]
}

// ============================================================================
// Builder
// ============================================================================

fn build_cargo_toml(ctx: &GenerationContext) -> String {
    let pkg = ctx.package_name();
    let edition = ctx.rust_edition();
    let db = ctx.database();
    let auth_enabled = ctx.auth_enabled();
    let openapi = ctx.openapi_enabled();

    let mut out = String::with_capacity(2048);

    // ── Header comment ───────────────────────────────────────────────────
    out.push_str(
        "# =============================================================================\n",
    );
    out.push_str(&format!("# {} — Generated by Immortal Engine v2.0\n", pkg));
    out.push_str(
        "# =============================================================================\n\n",
    );

    // ── [package] ────────────────────────────────────────────────────────
    out.push_str("[package]\n");
    out.push_str(&format!("name = \"{}\"\n", pkg));
    out.push_str("version = \"0.1.0\"\n");
    out.push_str(&format!("edition = \"{}\"\n", edition));

    if let Some(desc) = &ctx.meta.description {
        out.push_str(&format!("description = \"{}\"\n", escape_toml_string(desc)));
    }
    if let Some(author) = &ctx.meta.author {
        out.push_str(&format!("authors = [\"{}\"]\n", escape_toml_string(author)));
    }

    out.push_str("publish = false\n");
    out.push('\n');

    // ── [dependencies] ───────────────────────────────────────────────────
    out.push_str("[dependencies]\n");

    // -- Web framework --
    out.push_str("# Web framework\n");
    out.push_str("axum = { version = \"0.8\", features = [\"macros\"] }\n");

    let mut tower_http_features = vec!["\"trace\""];
    if ctx.config.cors_enabled {
        tower_http_features.push("\"cors\"");
    }
    tower_http_features.push("\"timeout\"");
    out.push_str(&format!(
        "tower-http = {{ version = \"0.6\", features = [{}] }}\n",
        tower_http_features.join(", ")
    ));
    out.push_str("tower = \"0.5\"\n");
    out.push('\n');

    // -- Async runtime --
    out.push_str("# Async runtime\n");
    out.push_str("tokio = { version = \"1\", features = [\"full\"] }\n");
    out.push('\n');

    // -- ORM & Database --
    out.push_str("# ORM & Database\n");

    let sea_orm_db_feature = match db {
        DatabaseType::PostgreSQL => "sqlx-postgres",
        DatabaseType::MySQL => "sqlx-mysql",
        DatabaseType::SQLite => "sqlx-sqlite",
    };
    out.push_str(&format!(
        "sea-orm = {{ version = \"1.1\", features = [\"runtime-tokio-rustls\", \"{}\", \"macros\"] }}\n",
        sea_orm_db_feature
    ));
    out.push('\n');

    // -- Serialization --
    out.push_str("# Serialization\n");
    out.push_str("serde = { version = \"1\", features = [\"derive\"] }\n");
    out.push_str("serde_json = \"1\"\n");
    out.push('\n');

    // -- Validation --
    out.push_str("# Validation\n");
    out.push_str("validator = { version = \"0.19\", features = [\"derive\"] }\n");
    out.push('\n');

    // -- Identifiers --
    out.push_str("# Identifiers\n");
    out.push_str("uuid = { version = \"1\", features = [\"v4\", \"serde\"] }\n");
    out.push('\n');

    // -- Date/Time --
    out.push_str("# Date/Time\n");
    out.push_str("chrono = { version = \"0.4\", features = [\"serde\"] }\n");
    out.push('\n');

    // -- Error handling --
    out.push_str("# Error handling\n");
    out.push_str("thiserror = \"2\"\n");
    out.push_str("anyhow = \"1\"\n");
    out.push('\n');

    // -- Logging --
    out.push_str("# Logging\n");
    out.push_str("tracing = \"0.1\"\n");
    out.push_str("tracing-subscriber = { version = \"0.3\", features = [\"env-filter\"] }\n");
    out.push('\n');

    // -- Configuration --
    out.push_str("# Configuration\n");
    out.push_str("dotenvy = \"0.15\"\n");
    out.push('\n');

    // -- Auth (conditional) --
    if auth_enabled {
        out.push_str("# Authentication\n");
        match ctx.auth_strategy() {
            AuthStrategy::Jwt | AuthStrategy::ApiKey => {
                out.push_str("jsonwebtoken = \"9\"\n");
                out.push_str(
                    "axum-extra = { version = \"0.10\", features = [\"typed-header\"] }\n",
                );
                out.push_str("bcrypt = \"0.16\"\n");
            }
            AuthStrategy::Session => {
                out.push_str("axum-extra = { version = \"0.10\", features = [\"cookie\"] }\n");
                out.push_str("bcrypt = \"0.16\"\n");
            }
            AuthStrategy::None => {}
        }
        out.push('\n');
    }

    // -- OpenAPI (conditional) --
    if openapi {
        out.push_str("# OpenAPI / Swagger\n");
        out.push_str("utoipa = { version = \"5\", features = [\"axum_extras\"] }\n");
        out.push_str("utoipa-swagger-ui = { version = \"8\", features = [\"axum\"] }\n");
        out.push('\n');
    }

    // ── [dev-dependencies] ───────────────────────────────────────────────
    if ctx.generate_tests() {
        out.push_str("[dev-dependencies]\n");
        out.push_str("# Testing\n");
        out.push_str("tokio-test = \"0.4\"\n");
        out.push_str("reqwest = { version = \"0.12\", features = [\"json\"] }\n");
        out.push_str("serial_test = \"3\"\n");
        out.push('\n');
    }

    // ── [profile.release] ────────────────────────────────────────────────
    out.push_str("[profile.release]\n");
    out.push_str("opt-level = 3\n");
    out.push_str("lto = true\n");
    out.push_str("strip = true\n");
    out.push_str("codegen-units = 1\n");

    out
}

// ============================================================================
// Helpers
// ============================================================================

/// Escape a string for TOML double-quoted values.
fn escape_toml_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use imortal_ir::{AuthConfig, AuthStrategy, DatabaseType, ProjectGraph};

    #[test]
    fn test_generate_cargo_toml_basic() {
        let project = ProjectGraph::new("my_api");
        let ctx = GenerationContext::from_project_default(&project);
        let files = generate_cargo_toml(&ctx);

        assert_eq!(files.len(), 1);
        assert_eq!(files[0].path.to_string_lossy(), "Cargo.toml");

        let content = &files[0].content;
        assert!(content.contains("[package]"));
        assert!(content.contains("name = \"my_app\""));
        assert!(content.contains("[dependencies]"));
        assert!(content.contains("axum"));
        assert!(content.contains("sea-orm"));
        assert!(content.contains("serde"));
        assert!(content.contains("tokio"));
        assert!(content.contains("uuid"));
        assert!(content.contains("tracing"));
        assert!(content.contains("validator"));
        assert!(content.contains("thiserror"));
        assert!(content.contains("dotenvy"));
    }

    #[test]
    fn test_generate_cargo_toml_postgresql() {
        let mut project = ProjectGraph::new("pg_app");
        project.config.database = DatabaseType::PostgreSQL;

        let ctx = GenerationContext::from_project_default(&project);
        let files = generate_cargo_toml(&ctx);
        let content = &files[0].content;

        assert!(content.contains("sqlx-postgres"));
        assert!(!content.contains("sqlx-mysql"));
        assert!(!content.contains("sqlx-sqlite"));
    }

    #[test]
    fn test_generate_cargo_toml_mysql() {
        let mut project = ProjectGraph::new("my_app");
        project.config.database = DatabaseType::MySQL;

        let ctx = GenerationContext::from_project_default(&project);
        let files = generate_cargo_toml(&ctx);
        let content = &files[0].content;

        assert!(content.contains("sqlx-mysql"));
        assert!(!content.contains("sqlx-postgres"));
    }

    #[test]
    fn test_generate_cargo_toml_sqlite() {
        let mut project = ProjectGraph::new("my_app");
        project.config.database = DatabaseType::SQLite;

        let ctx = GenerationContext::from_project_default(&project);
        let files = generate_cargo_toml(&ctx);
        let content = &files[0].content;

        assert!(content.contains("sqlx-sqlite"));
    }

    #[test]
    fn test_generate_cargo_toml_with_auth() {
        let mut project = ProjectGraph::new("secure_api");
        project.config.auth = AuthConfig::jwt();

        let ctx = GenerationContext::from_project_default(&project);
        let files = generate_cargo_toml(&ctx);
        let content = &files[0].content;

        assert!(content.contains("jsonwebtoken"));
        assert!(content.contains("axum-extra"));
        assert!(content.contains("bcrypt"));
    }

    #[test]
    fn test_generate_cargo_toml_without_auth() {
        let mut project = ProjectGraph::new("public_api");
        project.config.auth.enabled = false;

        let ctx = GenerationContext::from_project_default(&project);
        let files = generate_cargo_toml(&ctx);
        let content = &files[0].content;

        assert!(!content.contains("jsonwebtoken"));
        assert!(!content.contains("bcrypt"));
    }

    #[test]
    fn test_generate_cargo_toml_with_openapi() {
        let mut project = ProjectGraph::new("docs_api");
        project.config.openapi_enabled = true;

        let ctx = GenerationContext::from_project_default(&project);
        let files = generate_cargo_toml(&ctx);
        let content = &files[0].content;

        assert!(content.contains("utoipa"));
        assert!(content.contains("utoipa-swagger-ui"));
    }

    #[test]
    fn test_generate_cargo_toml_without_openapi() {
        let mut project = ProjectGraph::new("no_docs_api");
        project.config.openapi_enabled = false;

        let ctx = GenerationContext::from_project_default(&project);
        let files = generate_cargo_toml(&ctx);
        let content = &files[0].content;

        assert!(!content.contains("utoipa"));
    }

    #[test]
    fn test_generate_cargo_toml_with_cors() {
        let mut project = ProjectGraph::new("cors_api");
        project.config.cors_enabled = true;

        let ctx = GenerationContext::from_project_default(&project);
        let files = generate_cargo_toml(&ctx);
        let content = &files[0].content;

        assert!(content.contains("\"cors\""));
    }

    #[test]
    fn test_generate_cargo_toml_with_tests() {
        let project = ProjectGraph::new("test_api");
        let ctx = GenerationContext::from_project_default(&project);
        let files = generate_cargo_toml(&ctx);
        let content = &files[0].content;

        assert!(content.contains("[dev-dependencies]"));
        assert!(content.contains("tokio-test"));
        assert!(content.contains("reqwest"));
    }

    #[test]
    fn test_generate_cargo_toml_without_tests() {
        let project = ProjectGraph::new("test_api");
        let config = crate::GeneratorConfig::new().without_tests();
        let ctx = GenerationContext::from_project(&project, config);
        let files = generate_cargo_toml(&ctx);
        let content = &files[0].content;

        assert!(!content.contains("[dev-dependencies]"));
    }

    #[test]
    fn test_generate_cargo_toml_release_profile() {
        let project = ProjectGraph::new("prod_api");
        let ctx = GenerationContext::from_project_default(&project);
        let files = generate_cargo_toml(&ctx);
        let content = &files[0].content;

        assert!(content.contains("[profile.release]"));
        assert!(content.contains("lto = true"));
        assert!(content.contains("strip = true"));
    }

    #[test]
    fn test_generate_cargo_toml_session_auth() {
        let mut project = ProjectGraph::new("session_api");
        project.config.auth = AuthConfig::session();

        let ctx = GenerationContext::from_project_default(&project);
        let files = generate_cargo_toml(&ctx);
        let content = &files[0].content;

        assert!(content.contains("axum-extra"));
        assert!(content.contains("cookie"));
        assert!(content.contains("bcrypt"));
        // Session auth should NOT include jsonwebtoken
        assert!(!content.contains("jsonwebtoken"));
    }

    #[test]
    fn test_escape_toml_string() {
        assert_eq!(escape_toml_string("hello"), "hello");
        assert_eq!(escape_toml_string("he\"llo"), "he\\\"llo");
        assert_eq!(escape_toml_string("he\\llo"), "he\\\\llo");
        assert_eq!(escape_toml_string("line1\nline2"), "line1\\nline2");
    }

    #[test]
    fn test_generate_cargo_toml_with_metadata() {
        let mut project = ProjectGraph::new("meta_api");
        project.meta.description = Some("A great API".to_string());
        project.meta.author = Some("Jane Doe".to_string());

        let ctx = GenerationContext::from_project_default(&project);
        let files = generate_cargo_toml(&ctx);
        let content = &files[0].content;

        assert!(content.contains("description = \"A great API\""));
        assert!(content.contains("authors = [\"Jane Doe\"]"));
    }
}
